.\" $Id$

.\" osie is a tool to extract metadata from OpenTTD's screenshots.
.\" Copyright (C) 2010  Remko Bijker
.\"
.\" This manual page is free software.  It is distributed under the
.\" terms of the GNU General Public License as published by the Free
.\" Software Foundation; either version 2 of the License.
.\"
.\" This manual page is distributed in the hope that it will be useful,
.\" but WITHOUT ANY WARRANTY; without even the implied warranty of
.\" MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
.\" GNU General Public License for more details.
.\"
.\" You should have received a copy of the GNU General Public License
.\" along with this manual page; if not, write to the Free Software
.\" Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301
.\" USA
.\"
.Dd December 21, 2010
.Dt OSIE 1
.Sh NAME
.Nm osie
.Nd An open source tool to extract metadata from OpenTTD's screenshots
.Sh SYNOPSIS
.Nm
.Ar sample_file
.Sh DESCRIPTION
osie (OpenTTD screenshot information extractor) extracts metadata from
OpenTTD's PNG screenshots. You pass it an OpenTTD screenshot and it will
print the metadata to the console.
.Sh SEE ALSO
.Nm openttd Ns (1)
the game that creates screenshots with the metadata.
.sp
.Sh AUTHORS
.An Remko Bijker
.Aq rubidium@openttd.org
